### ISSUE TITLE
User input not correctly recognized

### ISSUE THREAD

**Issue by ThinkPadNL** [docbender/Onkyo-RI#2]
Hi,

I was trying the test sketch. However, user input doesn't seems to be recognized correctly by the code.
I entered **0x2B0** (set dimmer to high), but the Serial Monitor showed me: _user - 0x20_. So it is not parsed correctly by the sketch.

What needs to be adjusted in the code to let user commands work correctly?

**Comment by docbender** [comment]
Hi, 
I forgot to check capital letters in user input. Only lowercase was supported (ex. 0x2b0). I was extended it now to capital letters as well.
