### ISSUE TITLE
RI codes for "Radio (FM) input" and "Power On + Radio Input (FM)" are missing.

### ISSUE THREAD

**Issue by S1N4X** [docbender/Onkyo-RI#4]
The hex RI codes for "Radio (FM) input" and "Power On + Radio Input (FM)" are missing. 
Do they exist and have not been found or they don't?

Thanks

**Comment by docbender** [comment]
I can't talk about all devices. My device TX8020 lacks this commands

**Comment by S1N4X** [comment]
I should have specified it but my device is also TX-8020. That’s too bad. Thanks for your answer!

**Comment by docbender** [comment]
Yeah it sucks. Onkyo designed it to control remote audio sources. Not receiver itself :-(
