### ISSUE TITLE
Onkyo TX-SR309

### ISSUE THREAD

**Issue by ant-thomas** [docbender/Onkyo-RI#5]
Just wondering if anyone has made this work with a TX-SR309?

Got a mono jack and wired it up to test, ran the test program but no codes turn on the receiver.

**Comment by docbender** [comment]
Hi, I have no experience with this TX type, but it has RI port so it should work. Maybe you can ask @oelegeirnaert who tried it with SR-307 (https://github.com/docbender/Onkyo-RI/issues/3 )
Best

5. 2. 2019 23:31, 23:31, ant-thomas <notifications@github.com> napsal/a:
