### ISSUE TITLE
TX-SR600

### ISSUE THREAD

**Issue by kelvinlaw** [docbender/Onkyo-RI#6]
Hi - I have experimented a little on my TX-SR600 and can confirm the following. Hope this helps somebody.

**These commands work (there may be others):**
0x1AE = turn off amp to standby (only works if you are currently in Video 3!!)
0x1A0 = video 3
0x1AF = turn on + go to video 3
0x20 = CD
0x2F = Turn on + go to CD
0x120 = DVD
0x12F = Turn on + go to DVD
0x70 = TAPE
0x7F = Turn on + go to TAPE

**These commands DON'T WORK:
(https://github.com/docbender/Onkyo-RI)**
0x170 = Input DOCK
0x17F = Turn on + Input DOCK
0x420 = Turn Off
0x421-424 = Test mode

**These commands DON"T WORK:
(http://lirc.sourceforge.net/remotes/onkyo/Remote_Interactive)**
0x0804 = MD_On
0x00E9 = AMP_On
0x00EA = Amp_Standby
0x0AA1 = Amp_Muting

**Comment by jimtng** [comment]
TX-SR603 here

0x1A0 Input Video 3
0x1A2 Volume Up (only when input is set to Video 3)
0x1A3 Volume Down  (only when input is set to Video 3)
0x1A4 Mute  (only when input is set to Video 3)
0x1A5 Unmute  (only when input is set to Video 3)
0x1AE Standby/turn off  (only when input is set to Video 3)
0x1AF Turn on and switch to Video 3

**Comment by docbender** [comment]
Thank you for your contribution. I added it into readme.
