### ISSUE TITLE
Codes list for Onkyo TX-SR304

### ISSUE THREAD

**Issue by lonejeeper** [docbender/Onkyo-RI#7]
Here's what I've found for my older Onkyo TX-SR304, might save someone some time:

0x20 - CD
0x70 - TAPE
0x120 - DVD
0x170 - HDD
0x1A0 - Video2
0x1A2 - Vol UP
0x1A3 - Vol DOWN
0x1A4 - MUTE
0x1AE  - POWER OFF
0x1AF - POWER ON
0x2b0 - dim
0x2b1 - dimer
0x2b2 - dimmest
0x2b8 - daytime brightness
0x2BF - nighttime brightness

0x421 - RDS TEST 1-00 (FM MEMORY?)
0x422 - RDS TEST 2-00
0x423 - RDS Test 3-00 
0x430 - RDS Test 4 (BEEEEEEEEEEP)
And I stopped after the crazy loud high-pitched tone.

**Comment by docbender** [comment]
Thanks for the contribution
